apiVersion: batch/v1
kind: Job
metadata:
  name: {NAME}
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  backoffLimit: 1  # How many times to try to run the job until giving up
  template:
    metadata:
      name: {NAME}
    spec:
      securityContext:
        runAsUser: {USER_ID}
        runAsGroup: {GROUP_ID}
      priorityClassName: interactive
      containers:
      - name: devbox-container
        image: "{IMAGE}"
        imagePullPolicy: Always
        command:
          - bash
          - -c
          - |
            sleep 2d
        resources:
          requests:
            cpu: {CPU}
          limits:
            memory: "{MEMORY}"
            nvidia.com/gpu: {GPU}
        env:
        - name: OMP_NUM_THREADS
          value: "{CPU}"
        - name: WANDB_MODE
          value: offline
        - name: WANDB_PROJECT
          value: "{WANDB_PROJECT}"
        - name: WANDB_ENTITY
          value: farai
        - name: HF_HOME
          value: "/training/hf_home"
        - name: WANDB_RUN_GROUP
          value: devbox
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface
              key: token
        volumeMounts:
        - name: training
          mountPath: /training
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: training
        persistentVolumeClaim:
          claimName: repepo
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 10Gi
      restartPolicy: Never
      imagePullSecrets:
      - name: docker
