apiVersion: batch/v1
kind: Job
metadata:
  name: {NAME}
  labels:
    kueue.x-k8s.io/queue-name: farai
spec:
  suspend: true
  backoffLimit: 0  # Never retry the pod on error
  # Make sure to retry the pod if the pod/job is preempted
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget

  template:
    metadata:
      name: {NAME}
    spec:
      securityContext:
        runAsUser: {USER_ID}
        runAsGroup: {GROUP_ID}
      priorityClassName: interactive
      containers:
      - name: devbox-container
        image: "{IMAGE}"
        imagePullPolicy: Always
        command:
          - bash
          - -c
          - |
            git pull
            git checkout {COMMIT_HASH}
            git submodule update --recursive
            sleep 2d
        resources:
          requests:
            cpu: {CPU}
          limits:
            memory: "{MEMORY}"
            nvidia.com/gpu: {GPU}
        env:
        - name: OMP_NUM_THREADS
          value: "{CPU}"
        - name: HF_HOME
          value: "/hf-cache/hf_home"
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: huggingface
              key: token
        volumeMounts:
        - name: training
          mountPath: /training
        - name: hf-cache
          mountPath: /hf-cache
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: training
        persistentVolumeClaim:
          claimName: az-repepo
      - name: hf-cache
        persistentVolumeClaim:
          claimName: local-repepo
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 10Gi
      restartPolicy: Never
