apiVersion: batch/v1
kind: Job
metadata:
  name: {NAME}
  labels:
    kueue.x-k8s.io/queue-name: farai
    wandb-group: {WANDB_RUN_GROUP}
    wandb-project: {WANDB_PROJECT}
    wandb-job-name: {WANDB_JOB_NAME}
    wandb-entity: {WANDB_ENTITY}
    launch-id: {LAUNCH_ID}
spec:
  suspend: true
  backoffLimit: 0  # Never retry the pod on error
  # Make sure to retry the pod if the pod/job is preempted
  podFailurePolicy:
    rules:
    - action: Ignore
      onPodConditions:
      - type: DisruptionTarget

  template:
    metadata:
      generateName: {NAME}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      priorityClassName: {PRIORITY}
      containers:
      - name: devbox-container
        image: "ghcr.io/dtch1997/repepo:{CONTAINER_TAG}"
        imagePullPolicy: Always
        command:
          - bash
          - -c
          - |
            git pull
            git checkout {COMMIT_HASH}
            git submodule update --recursive
            {COMMAND}
        resources:
          requests:
            cpu: {CPU}
          limits:
            memory: {MEMORY}
            nvidia.com/gpu: {GPU}
        env:
        - name: OMP_NUM_THREADS
          value: {OMP_NUM_THREADS}
        - name: GIT_ASKPASS
          value: "true"
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-credentials
              key: pat
        - name: GIT_CONFIG_PARAMETERS
          value: "'credential.https://github.com.username=$(GITHUB_PAT)'"
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb
              key: api-key
        - name: WANDB_ENTITY
          value: {WANDB_ENTITY}
        - name: WANDB_JOB_NAME
          value: {WANDB_JOB_NAME}
        - name: WANDB_PROJECT
          value: {WANDB_PROJECT}
        - name: WANDB_RUN_GROUP
          value: {WANDB_RUN_GROUP}
        - name: WANDB_MODE
          value: {WANDB_MODE}
        volumeMounts:
        - name: training
          mountPath: {TRAINING_MOUNT}
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: training
        persistentVolumeClaim:
          claimName: repepo
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 10Gi
      restartPolicy: Never
