apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repepo-local
  namespace: u-repepo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: repepo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repepo
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /export/repepo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01

