name: 'ci'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository_owner }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm install

      - name: Lint
        run: pre-commit run --all-files

      - name: Test
        run: python -m pytest tests
