name: "ci"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.repository_owner }}-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install PDM
        run: python -m pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Lint
        run: pdm run pre-commit run --all-files

      - name: Type check
        run: pdm run pyright

      - name: Test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: pdm run python -m pytest tests
